#!/usr/bin/perl -w
#
# csv-to-gct.pl
#
# Converts Comma Delimmited file (*.csv) generated by OpenArray Real-Time 
# Analysis Software to Gene Cluster Text file format (*.gct) so it can be
# used for Broad Institute's Gene Set Enrichment Analysis (GSEA) program.
# Phenotype Data Format files (*.cls) as well as Gene Set Database format
# (*.gmx, *.gmt, or *.grp) may be generated with an optional parameter.
#
# Last updated: 11.08.2012
# -----

